# Generated by Django 5.1.1 on 2024-10-15 05:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='snippit_share',
            fields=[
                ('code_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_file', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(max_length=10)),
                ('create_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
